<?php
/**
 * @version 3.4.1 2015-05-26
 * @package Joomla
 * @subpackage KnowledgeBase
 * @copyright (C) 2015 the Thinkery LLC. All rights reserved.
 * @license GNU/GPL see LICENSE
 */

defined('_JEXEC' ) or die('Restricted access');
jimport('joomla.application.component.controller');
jimport('joomla.error.log');

class knowledgebaseController extends JControllerLegacy
{
    var $log;
    var $debug;

    public function __construct()
    {
        $this->debug = false;
        if($this->debug) $this->log =JLog::getInstance('iproperty.log.php'); // create the logfile TODO: maybe add a debug switch to the admin to turn this off or on
        if($this->debug) $this->log->addEntry(array('COMMENT' => 'Constructing IProperty'));

        parent::__construct();
    }

    public function display($cachable = false, $urlparams = false)
    {
        $app            = JFactory::getApplication();
        $document       = JFactory::getDocument();
        $settings       = ipropertyAdmin::config();
        $ipversion      = ipropertyAdmin::_getversion();
        ipropertyHTML::includeIpScripts();

        if( $settings->offline == 1 ){
            echo '
                <div align="center" class="kb-offline">
                    '.JHtml::_('image', 'components/com_iproperty/assets/images/iproperty.png', JText::_('COM_IPROPERTY_NO_ACCESS')).'
                    <div>' . $settings->offmessage . '</div>
                </div>';
        }else{
            // make sure bootstrap framework and css is loaded
            JHtml::_('bootstrap.framework');

            if($settings->bootstrap_css){
                $lang = JFactory::getLanguage();
                $lang_direction = $lang->isRTL() ? 'rtl' : 'ltr';
                JHtml::_('bootstrap.loadCss', true, $lang_direction);
            }

            $cachable       = ($app->input->getInt('ipquicksearch')) ? false : true;
            $editid         = $app->input->getUint('id');
            $vName          = $app->input->getCmd('view', 'home');

            // add additional models for manage view
            if ($vName == 'manage')
            {
                $vType       = $document->getType();
                $view        = $this->getView($vName, $vType);

                switch($app->input->get('layout'))
                {
                    case 'proplist':
                    default:
                        $model = $this->getModel('proplist', 'ipropertymodel');
                        break;
                    case 'agentlist':
                        $model = $this->getModel('agentlist', 'ipropertymodel');
                        break;
                    case 'companylist':
                        $model = $this->getModel('companylist', 'ipropertymodel');
                        break;
                    case 'openhouselist':
                        $model = $this->getModel('openhouselist', 'ipropertymodel');
                        break;
                }
                $view->setModel($model, true);
            }

            $app->input->set('view', $vName);

            $safeurlparams = array('cat'=>'INT','id'=>'INT','cid'=>'ARRAY','limit'=>'INT','limitstart'=>'INT',
                'showall'=>'INT','return'=>'BASE64','search'=>'STRING','filter_order'=>'CMD','filter_order_dir'=>'CMD','filter_order_Dir'=>'CMD',
                'print'=>'BOOLEAN','lang'=>'CMD');

            if ($vName !== 'feed') echo '<!-- Generated by KnowledgeBase v'.$ipversion['iproperty'].' by The Thinkery LLC. http://iproperty.thethinkery.net -->';
            parent::display($cachable, $safeurlparams);

            return $this;
        }
    }
}
